{application,civo,
             [{applications,[kernel,stdlib,elixir,logger,httpoison,poison,
                             exvcr,ex_doc]},
              {description,"Elixir wrapper of the Civo hosting API."},
              {modules,['Elixir.Civo','Elixir.Civo.Charges','Elixir.Civo.DNS',
                        'Elixir.Civo.Error','Elixir.Civo.Firewalls',
                        'Elixir.Civo.Instances','Elixir.Civo.Kubernetes',
                        'Elixir.Civo.LoadBalancers','Elixir.Civo.Networks',
                        'Elixir.Civo.Quota','Elixir.Civo.Regions',
                        'Elixir.Civo.Request','Elixir.Civo.Response',
                        'Elixir.Civo.SSH','Elixir.Civo.Snapshots',
                        'Elixir.Civo.Templates','Elixir.Civo.Volumes',
                        'Elixir.Civo.WebHooks']},
              {registered,[]},
              {vsn,"0.1.1"}]}.
